name: Release with changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to fetch full history for changelog

      - name: Install git-chglog
        run: |
          wget https://github.com/git-chglog/git-chglog/releases/latest/download/git-chglog_Linux_x86_64.tar.gz
          tar -xzf git-chglog_Linux_x86_64.tar.gz
          sudo mv git-chglog /usr/local/bin/

      - name: Generate changelog
        run: git-chglog -o CHANGELOG.md

      - name: Commit changelog if updated
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git diff --quiet CHANGELOG.md || (git add CHANGELOG.md && git commit -m "chore: update CHANGELOG.md for ${{ github.ref_name }}" && git push)

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -c Release -o ./publish

      - name: Zip publish folder
        run: zip -r cams.zip ./publish

      - name: Read changelog content for release notes
        id: changelog
        run: echo "content<<EOF" >> $GITHUB_OUTPUT && head -n 100 CHANGELOG.md >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.content }}
          files: cams.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
